title: &ensp;Maja Jurcan
logo: "/images/logo.png?raw=true"
description: >
  Meticulous and motivated computer engineer possessing good technical skills rooted in substantial training and education. Looking to use 800 hours of training at a Data Analytics and Machine Learning bootcamp to implement machine learning and data-driven solutions at your organization.
#show_downloads: false


theme: jekyll-theme-minimal

