title: <p> MAJA JURCAN </p> 
logo: "/images/analytics.jpg?raw=true"
description: >
  <br><br>
  Meticulous and motivated computer engineer possessing good technical skills rooted in substantial training and education.
  <br><br>
  Looking to use 800 hours of training at a Data Analytics and Machine Learning bootcamp to implement machine learning and data-driven solutions at your organization.
  <br><br>
  <a href="/pdf/portfolio.pdf">View My Older Projects</a> 


theme: jekyll-theme-minimal

