title: MAJA JURCAN
logo: "/images/analytics.png?raw=true"
description: >
  <br><br>
  Meticulous and motivated computer engineer possessing good technical skills rooted in substantial training and education.
  <br><br>
  Looking to use 800 hours of training at a Data Analytics and Machine Learning bootcamp to implement machine learning and data-driven solutions at your organization.
  <br><br>


theme: jekyll-theme-minimal

